title: Site title appears here.
description: Blah blah description. Blah Blah description.
lsi: false
safe: true
source: docs
incremental: false
highlighter: rouge
show_downloads: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
